<?php
require 'BaseConnection.php';

require 'login/ApiLogin.php';
require 'AppMemeControl.php';
require 'enregistrement/clients/AppInsertionClient.php';
require 'enregistrement/techniciens/AppInsertionTechnicien.php';
require 'enregistrement/vehicules/AppInsertionVehicule.php';
require 'reception/AppInsertionReception.php';
require 'programmation/AppInsertionProgrammation.php';
require 'operateur/AppInsertOperateurs.php';
require 'observation/pointage/AppInsertionPointage.php';
require 'observation/recommandation/AppInsertionRecommandation.php';
require 'observation/inspection/AppInsertionInspection.php';
require 'ordreDeReparation/travauxRealises/AppInsertionActivite.php';
require 'livraison/AppInsertionLivraison.php';
require 'observation/reclamation/AppInsertionReclamation.php';
require 'ordreDeReparation/maintenance/AppInsertionMaintenance.php';
require 'administrateur/AppInsertionUtilisateur.php';
require 'enregistrement/alerts/AppInsertionXvehiculeRevision.php';
require 'enregistrement/alerts/AppInsertionXVehiculeVisiteTechnique.php';
require 'enregistrement/alerts/AppInsertionXvehiculeAssurance.php';
require 'enregistrement/alerts/AppInsertionXvehiculeGarantie.php';
require 'ordreDeReparation/maintenanceStandard/AppInsertionMaintenanceStandard.php';

require 'ordreDeReparation/maintenance/AppSuppressionMaintenance.php';
require 'observation/inspection/AppSuppressionInspection.php';
require 'observation/recommandation/AppSuppressionRecommandation.php';
require 'observation/reclamation/AppSuppressionReclamation.php';
require 'livraison/AppSuppressionLivraison.php';
require 'reception/AppSuppressionReception.php';
require 'ordreDeReparation/travauxRealises/AppSuppressionActivite.php';
require 'programmation/AppSuppressionProgrammation.php';
require 'enregistrement/vehicules/AppSuppressionVehicule.php';
require 'enregistrement/clients/AppSuppressionClient.php';
require 'enregistrement/techniciens/AppSuppressionTechnicien.php';
require 'observation/pointage/AppSuppressionPointage.php';
require 'operateur/AppSuppressionOperateurs.php';
require 'enregistrement/alerts/AppSuppressionXvehiculeRevision.php';
require 'enregistrement/alerts/AppSuppressionXvehiculeVisiteTechnique.php';
require 'enregistrement/alerts/AppSuppressionXvehiculeAssurance.php';
require 'enregistrement/alerts/AppSuppressionXvehiculeGarantie.php';
require 'ordreDeReparation/maintenanceStandard/AppSuppressionMaintenanceStandard.php';

require 'ordreDeReparation/maintenance/AppModificationMaintenance.php';
require 'observation/inspection/AppModificationInspection.php';
require 'observation/recommandation/AppModificationRecommandation.php';
require 'observation/reclamation/AppModificationReclamation.php';
require 'livraison/AppModificationLivraison.php';
require 'reception/AppModificationReception.php';
require 'ordreDeReparation/evolutionDesTravaux/AppModificationEvolution.php';
require 'programmation/AppModificationProgrammation.php';
require 'enregistrement/clients/AppModificationClient.php';
require 'enregistrement/vehicules/AppModificationVehicule.php';
require 'enregistrement/techniciens/AppModificationTechnicien.php';
require 'ordreDeReparation/travauxRealises/AppModificationActivite.php';
require 'observation/pointage/AppModificationPointage.php';
require 'operateur/AppModificationOperateurs.php';
require 'enregistrement/alerts/AppModificationXvehiculeRevision.php';
require 'enregistrement/alerts/AppModificationXvehiculeVisiteTechnique.php';
require 'enregistrement/alerts/AppModificationXvehiculeAssurance.php';
require 'enregistrement/alerts/AppModificationXvehiculeGarantie.php';
require 'ordreDeReparation/maintenanceStandard/AppModificationMaintenanceStandard.php';

require 'enregistrement/alerts/ApEtatVisibiliteVehiculeRevision.php';
require 'enregistrement/alerts/ApEtatVisibiliteVehiculeAssurance.php';
require 'enregistrement/alerts/ApEtatVisibiliteVehiculeGarantie.php';
require 'enregistrement/alerts/ApEtatVisibiliteVehiculeVisiteTechnique.php';

global $dbase;

$ApiLoggn  = new ApiLogin($dbase);
$ApiMemeContro = new AppMemeControl($dbase);
$ApiInsertClient = new AppInsertionClient($dbase);
$ApiInsertVehicule = new AppInsertionVehicule($dbase);
$ApiInserttTech = new AppInsertionTechnicien($dbase);
$ApiInsertProg = new AppInsertionProgrammation($dbase);
$ApiInsertRecep = new AppInsertionReception($dbase);
$ApiInsertOperateurs = new AppInsertOperateurs($dbase);
$ApiInsertPoint = new AppInsertionPointage($dbase);
$ApiInsertRecom = new AppInsertionRecommandation($dbase);
$ApiInsertInspect = new AppInsertionInspection($dbase);
$ApiInsertActiv = new AppInsertionActivite($dbase);
$ApiInsertLivre = new AppInsertionLivraison($dbase);
$ApiInsertReclam = new AppInsertionReclamation($dbase);
$ApiInsertMaint = new AppInsertionMaintenance($dbase);
$ApiInsertUtil = new AppInsertionUtilisateur($dbase);
$ApiInsertRevise = new AppInsertionXvehiculeRevision($dbase);
$ApiInsertVisite = new AppInsertionXVehiculeVisiteTechnique($dbase);
$ApiInsertAssure = new AppInsertionXvehiculeAssurance($dbase);
$ApiInsertGarant = new AppInsertionXvehiculeGarantie($dbase);
$ApiInsertMaintStand = new AppInsertionMaintenanceStandard($dbase);

$SupMaint = new AppSuppressionMaintenance($dbase);
$SupInspect = new AppSuppressionInspection($dbase);
$SupRecom = new AppSuppressionRecommandation($dbase);
$SupReclam = new AppSuppressionReclamation($dbase);
$SupLivre = new AppSuppressionLivraison($dbase);
$SupRecep = new AppSuppressionReception($dbase);
$SupActiv = new AppSuppressionActivite($dbase);
$SupProg = new AppSuppressionProgrammation($dbase);
$SupVehicule = new AppSuppressionVehicule($dbase);
$SupClient = new AppSuppressionClient($dbase);
$SupTech = new AppSuppressionTechnicien($dbase);
$SupPoint = new AppSuppressionPointage($dbase);
$SupOperateurs = new AppSuppressionOperateurs($dbase);
$SupRendRevise = new AppSuppressionXvehiculeRevision($dbase);
$SupRendVisTech = new AppSuppressionXvehiculeVisiteTechnique($dbase);
$SupRendAssure = new AppSuppressionXvehiculeAssurance($dbase);
$SupRendGarantie = new AppSuppressionXvehiculeGarantie($dbase);
$SupMaintStandar = new AppSuppressionMaintenanceStandard($dbase);

$ModifMaint = new AppModificationMaintenance($dbase);
$ModifIspect = new AppModificationInspection($dbase);
$ModifRecom = new AppModificationRecommandation($dbase);
$ModifReclam = new AppModificationReclamation($dbase);
$ModifLivre = new AppModificationLivraison($dbase);
$ModifRecep = new AppModificationReception($dbase);
$ModifEvolut = new AppModificationEvolution($dbase);
$ModifProg = new AppModificationProgrammation($dbase);
$ModifClient = new AppModificationClient($dbase);
$ModifVehicule = new AppModificationVehicule($dbase);
$ModifTech = new AppModificationTechnicien($dbase);
$ModifActiv = new AppModificationActivite($dbase);
$ModifPoint = new AppModificationPointage($dbase);
$ModifOperateurs = new AppModificationOperateurs($dbase);
$ModifVehRenRevise = new AppModificationXvehiculeRevision($dbase);
$ModifVehRenViseTech = new AppModificationXvehiculeVisiteTechnique($dbase);
$ModifVehRenAssure = new AppModificationXvehiculeAssurance($dbase);
$ModifVehRenGarantie = new AppModificationXvehiculeGarantie($dbase);
$ModifMaintStand = new AppModificationMaintenanceStandard($dbase);

$EtatVisibiliteRevision = new ApEtatVisibiliteVehiculeRevision($dbase);
$EtatVisibiliteAssurance = new ApEtatVisibiliteVehiculeAssurance($dbase);
$EtatVisibiliteGarantie = new ApEtatVisibiliteVehiculeGarantie($dbase);
$EtatVisibiliteVisiteTech = new ApEtatVisibiliteVehiculeVisiteTechnique($dbase);